// Generated by BUCKLESCRIPT VERSION 4.0.11, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Text$BsReactNative = require("bs-react-native/lib/js/src/components/text.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var Platform$BsReactNative = require("bs-react-native/lib/js/src/platform.js");
var StyleSheet$BsReactNative = require("bs-react-native/lib/js/src/styleSheet.js");
var SafeAreaView$BsReactNative = require("bs-react-native/lib/js/src/components/safeAreaView.js");

var match = Platform$BsReactNative.os(/* () */0) === /* Android */0;

var styles = StyleSheet$BsReactNative.create({
      appContainer: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.flex(1.0),
            /* :: */[
              Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#F5F5F6"])),
              /* :: */[
                Style$BsReactNative.marginTop(/* Pt */Block.__(0, [match ? 20.0 : 0.0])),
                /* [] */0
              ]
            ]
          ]),
      title: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.fontSize(/* Float */Block.__(0, [19])),
            /* :: */[
              Style$BsReactNative.fontWeight(/* _600 */1056204983),
              /* :: */[
                Style$BsReactNative.textAlign(/* Center */3),
                /* [] */0
              ]
            ]
          ])
    });

function app(param) {
  return ReasonReact.element(undefined, undefined, Curry.app(SafeAreaView$BsReactNative.make, [
                  undefined,
                  undefined,
                  undefined,
                  undefined,
                  undefined,
                  undefined,
                  undefined,
                  undefined,
                  undefined,
                  Caml_option.some(styles.appContainer),
                  undefined,
                  undefined,
                  undefined,
                  undefined,
                  undefined,
                  undefined,
                  undefined,
                  undefined,
                  undefined,
                  undefined,
                  /* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(styles.title), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Let's get this party started!!!"]))]
                ]));
}

exports.styles = styles;
exports.app = app;
/* styles Not a pure module */
